# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/service_spec/style_transfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/service_spec/style_transfer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n)service/service_spec/style_transfer.proto\"\xa8\x01\n\x19TransferImageStyleRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05style\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontentSize\x18\x03 \x01(\x05\x12\x11\n\tstyleSize\x18\x04 \x01(\x05\x12\x15\n\rpreserveColor\x18\x05 \x01(\x08\x12\r\n\x05\x61lpha\x18\x06 \x01(\x02\x12\x0c\n\x04\x63rop\x18\x07 \x01(\x08\x12\x0f\n\x07saveExt\x18\x08 \x01(\t\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2K\n\rStyleTransfer\x12:\n\x14transfer_image_style\x12\x1a.TransferImageStyleRequest\x1a\x06.Imageb\x06proto3')
)




_TRANSFERIMAGESTYLEREQUEST = _descriptor.Descriptor(
  name='TransferImageStyleRequest',
  full_name='TransferImageStyleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='TransferImageStyleRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='style', full_name='TransferImageStyleRequest.style', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contentSize', full_name='TransferImageStyleRequest.contentSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='styleSize', full_name='TransferImageStyleRequest.styleSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preserveColor', full_name='TransferImageStyleRequest.preserveColor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='TransferImageStyleRequest.alpha', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crop', full_name='TransferImageStyleRequest.crop', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='saveExt', full_name='TransferImageStyleRequest.saveExt', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=214,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Image.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=237,
)

DESCRIPTOR.message_types_by_name['TransferImageStyleRequest'] = _TRANSFERIMAGESTYLEREQUEST
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransferImageStyleRequest = _reflection.GeneratedProtocolMessageType('TransferImageStyleRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERIMAGESTYLEREQUEST,
  __module__ = 'service.service_spec.style_transfer_pb2'
  # @@protoc_insertion_point(class_scope:TransferImageStyleRequest)
  ))
_sym_db.RegisterMessage(TransferImageStyleRequest)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'service.service_spec.style_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)



_STYLETRANSFER = _descriptor.ServiceDescriptor(
  name='StyleTransfer',
  full_name='StyleTransfer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=239,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='transfer_image_style',
    full_name='StyleTransfer.transfer_image_style',
    index=0,
    containing_service=None,
    input_type=_TRANSFERIMAGESTYLEREQUEST,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLETRANSFER)

DESCRIPTOR.services_by_name['StyleTransfer'] = _STYLETRANSFER

# @@protoc_insertion_point(module_scope)
