# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/model/style_transfer_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/model/style_transfer_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n&service/model/style_transfer_rpc.proto\"\xaa\x01\n\ninput_info\x12\x14\n\x0c\x63ontent_path\x18\x01 \x01(\t\x12\x12\n\nstyle_path\x18\x02 \x01(\t\x12\x19\n\x11output_image_size\x18\x03 \x01(\x05\x12\x19\n\x11start_from_random\x18\x04 \x01(\x08\x12\x1b\n\x13optimization_rounds\x18\x05 \x01(\x05\x12\x1f\n\x17optimization_iterations\x18\x06 \x01(\x05\"#\n\x05image\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t28\n\rStyleTransfer\x12\'\n\x0etransfer_style\x12\x0b.input_info\x1a\x06.image\"\x00\x62\x06proto3')
)




_INPUT_INFO = _descriptor.Descriptor(
  name='input_info',
  full_name='input_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_path', full_name='input_info.content_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='style_path', full_name='input_info.style_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_image_size', full_name='input_info.output_image_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_from_random', full_name='input_info.start_from_random', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optimization_rounds', full_name='input_info.optimization_rounds', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optimization_iterations', full_name='input_info.optimization_iterations', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=213,
)


_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='image.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='image.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=250,
)

DESCRIPTOR.message_types_by_name['input_info'] = _INPUT_INFO
DESCRIPTOR.message_types_by_name['image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input_info = _reflection.GeneratedProtocolMessageType('input_info', (_message.Message,), dict(
  DESCRIPTOR = _INPUT_INFO,
  __module__ = 'service.model.style_transfer_rpc_pb2'
  # @@protoc_insertion_point(class_scope:input_info)
  ))
_sym_db.RegisterMessage(input_info)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'service.model.style_transfer_rpc_pb2'
  # @@protoc_insertion_point(class_scope:image)
  ))
_sym_db.RegisterMessage(image)



_STYLETRANSFER = _descriptor.ServiceDescriptor(
  name='StyleTransfer',
  full_name='StyleTransfer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=252,
  serialized_end=308,
  methods=[
  _descriptor.MethodDescriptor(
    name='transfer_style',
    full_name='StyleTransfer.transfer_style',
    index=0,
    containing_service=None,
    input_type=_INPUT_INFO,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLETRANSFER)

DESCRIPTOR.services_by_name['StyleTransfer'] = _STYLETRANSFER

# @@protoc_insertion_point(module_scope)
