# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from service.model import style_transfer_rpc_pb2 as service_dot_model_dot_style__transfer__rpc__pb2


class StyleTransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.transfer_style = channel.unary_unary(
        '/StyleTransfer/transfer_style',
        request_serializer=service_dot_model_dot_style__transfer__rpc__pb2.input_info.SerializeToString,
        response_deserializer=service_dot_model_dot_style__transfer__rpc__pb2.image.FromString,
        )


class StyleTransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def transfer_style(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StyleTransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'transfer_style': grpc.unary_unary_rpc_method_handler(
          servicer.transfer_style,
          request_deserializer=service_dot_model_dot_style__transfer__rpc__pb2.input_info.FromString,
          response_serializer=service_dot_model_dot_style__transfer__rpc__pb2.image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'StyleTransfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
